apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-dcrx-kv-ingress"
  annotations:  
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules: 
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Release.Name }}-dcrx-kv"
            port:
              number: 2277