apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-dcrx-kv"
  labels:
    run: "{{ .Release.Name }}-dcrx-kv"
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 2278
      targetPort: 2278
  selector:
    app: "{{ .Release.Name }}-dcrx-kv"