# Default values for dcrx-kv.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 3

image:
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

env:
  DCRX_BOOT_WAIT: 10
  DCRX_KV_MAX_MEMORY_PERCENT_USAGE: 50
  DCRX_KV_JOB_PRUNE_INTERVAL: 1s
  DCRX_KV_JOB_MAX_AGE: 1m
  DCRX_KV_JOB_POOL_SIZE: 10
  DCRX_KV_JOB_WORKERS: 10
  DCRX_KV_TOKEN_EXPIRATION: 15m
  DCRX_KV_DATABASE_TYPE: asyncpg
  DCRX_KV_DATABASE_PORT: 5432
  DCRX_KV_DATABASE_USER: postgres


  
